# Generated by Django 5.0.14 on 2026-01-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybranch',
            name='biotime_code',
            field=models.CharField(blank=True, db_index=True, help_text='المعرّف الخارجي للفرع داخل نظام Biotime', max_length=64, null=True, verbose_name='Biotime Code'),
        ),
        migrations.AddField(
            model_name='companydepartment',
            name='biotime_code',
            field=models.CharField(blank=True, db_index=True, help_text='المعرّف الخارجي للقسم داخل نظام Biotime', max_length=64, null=True, verbose_name='Biotime Code'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='biotime_code',
            field=models.CharField(blank=True, db_index=True, help_text='المعرّف الخارجي للمسمى الوظيفي داخل نظام Biotime', max_length=64, null=True, verbose_name='Biotime Code'),
        ),
    ]
