# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب الشهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hrm_employees', to='company_manager.company', verbose_name='الشركة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف موظف',
                'verbose_name_plural': 'ملفات الموظفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
