# Generated by Django 5.0.14 on 2026-03-02 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_version', models.PositiveIntegerField(default=1, verbose_name='Session Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخر نشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة مستخدم نشطة',
                'verbose_name_plural': 'الجلسات النشطة',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['user'], name='auth_center_user_id_507852_idx'), models.Index(fields=['session_key'], name='auth_center_session_0ff718_idx'), models.Index(fields=['is_active'], name='auth_center_is_acti_24cd38_idx')],
            },
        ),
    ]
