# Generated by Django 5.0.14 on 2026-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0002_activeusersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الصورة'),
        ),
    ]
