# Generated by Django 5.0.14 on 2026-03-07 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0003_employeeprofile_avatar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='رابط الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activeusersession',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='activeusersession',
            name='auth_center_user_id_507852_idx',
        ),
        migrations.RemoveIndex(
            model_name='activeusersession',
            name='auth_center_session_0ff718_idx',
        ),
        migrations.RemoveIndex(
            model_name='activeusersession',
            name='auth_center_is_acti_24cd38_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
