# Generated by Django 5.0.14 on 2026-03-17 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_center', '0004_userprofile_alter_activeusersession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeusersession',
            options={'ordering': ['-last_seen'], 'verbose_name': 'جلسة مستخدم نشطة', 'verbose_name_plural': 'الجلسات النشطة'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب'),
        ),
        migrations.AddIndex(
            model_name='activeusersession',
            index=models.Index(fields=['user'], name='auth_center_user_id_507852_idx'),
        ),
        migrations.AddIndex(
            model_name='activeusersession',
            index=models.Index(fields=['session_key'], name='auth_center_session_0ff718_idx'),
        ),
        migrations.AddIndex(
            model_name='activeusersession',
            index=models.Index(fields=['is_active'], name='auth_center_is_acti_24cd38_idx'),
        ),
    ]
