# ================================================================
# 📘 LeaveAttendanceIntegrator — Primey HR Cloud V2 Ultra Pro
# ================================================================
# مسؤول عن:
# 1) تطبيق الإجازة على الحضور عند الموافقة (Apply)
# 2) إزالة أثر الإجازة عند الرفض/الإلغاء (Rollback)
# 3) دعم التعديل الجزئي لو تمت إعادة تحرير الإجازة لاحقًا
# 4) حماية سجلات Biotime الأصلية من الحذف أو التعديل
# 5) منع التضارب بين Leave ↔ Attendance أثناء المزامنة
# 6) دعم إعادة التصنيف الذكي للحضور بعد إزالة الإجازة
# ================================================================

from datetime import timedelta
from attendance_center.models import AttendanceRecord


class LeaveAttendanceIntegrator:

    def __init__(self, leave_request):
        self.leave = leave_request
        self.employee = leave_request.employee
        self.company = leave_request.company

    # ------------------------------------------------------------
    # 🟩 Helper — نطاق أيام الإجازة
    # ------------------------------------------------------------
    def _each_day(self):
        cur = self.leave.start_date
        while cur <= self.leave.end_date:
            yield cur
            cur += timedelta(days=1)

    # ------------------------------------------------------------
    # 🟦 1) Apply Leave → Attendance (V2)
    # ------------------------------------------------------------
    def apply_leave(self):
        """
        - يثبت أيام الإجازة كغياب مصرح به
        - يعدل السجلات الموجودة
        - يمنع Biotime من معالجتها لاحقًا
        """

        for day in self._each_day():

            record = AttendanceRecord.objects.filter(
                employee=self.employee,
                date=day
            ).first()

            # --------------------------------------------------------
            # 🔵 إذا السجل موجود ومصدره Biotime
            # --------------------------------------------------------
            if record and record.synced_from_biotime:
                record.status = "leave"
                record.is_leave = True
                record.is_locked = True          # 🆕 يمنع أي تعديل خارجي
                record.save()
                continue

            # --------------------------------------------------------
            # 🟡 سجل موجود لكنه ليس من Biotime
            # --------------------------------------------------------
            if record and not record.synced_from_biotime:
                record.status = "leave"
                record.is_leave = True
                record.is_locked = True          # 🆕 حماية إضافية
                record.synced_from_biotime = False
                record.save()
                continue

            # --------------------------------------------------------
            # 🟢 إنشاء سجل جديد (اليوم لم يسجل مسبقًا)
            # --------------------------------------------------------
            AttendanceRecord.objects.create(
                company=self.company,
                employee=self.employee,
                date=day,
                status="leave",
                is_leave=True,
                is_locked=True,            # 🆕 سجل محمي من التعديل
                synced_from_biotime=False,
                check_in=None,
                check_out=None,
                notes="Generated by LeaveApprovalEngine"
            )

    # ------------------------------------------------------------
    # 🟥 2) Rollback Leave → Attendance (V2)
    # ------------------------------------------------------------
    def rollback_leave(self):
        """
        - يحذف السجلات الناتجة عن الإجازة
        - يعيد سجلات Biotime لطبيعتها بدون حذف
        - يعيد التصنيف باستخدام محرك Attendance
        """

        for day in self._each_day():

            record = AttendanceRecord.objects.filter(
                employee=self.employee,
                date=day
            ).first()

            if not record:
                continue

            # --------------------------------------------------------
            # 🔵 سجل قادم من Biotime → لا يُحذف
            # --------------------------------------------------------
            if record.synced_from_biotime:
                record.is_leave = False
                record.is_locked = False     # السماح بإعادة التصنيف
                record.status = record.classify_status()
                record.save()
                continue

            # --------------------------------------------------------
            # 🟡 سجل مصنوع بسبب الإجازة فقط → يتم حذفه
            # --------------------------------------------------------
            if record.is_leave and not record.synced_from_biotime:
                record.delete()
                continue

            # --------------------------------------------------------
            # 🟠 سجل معدل يدويًا → نعيده لطبيعته
            # --------------------------------------------------------
            if record.is_locked:
                record.is_leave = False
                record.is_locked = False
                record.status = record.classify_status()
                record.save()
