# Generated by Django 5.0.14 on 2026-01-24 06:01

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='connected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
                ('overtime_enabled', models.BooleanField(default=True)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('auto_absent_if_no_checkin', models.BooleanField(default=True)),
                ('weekend_days', models.CharField(default='fri,sat', max_length=50)),
                ('weekly_hours_limit', models.PositiveIntegerField(default=48)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('weekend', 'عطلة أسبوعية'), ('unknown', 'غير معروف')], default='present', max_length=10)),
                ('late_minutes', models.IntegerField(default=0)),
                ('early_minutes', models.IntegerField(default=0)),
                ('overtime_minutes', models.IntegerField(default=0)),
                ('actual_hours', models.FloatField(default=0.0)),
                ('official_hours', models.FloatField(default=0.0)),
                ('reason_code', models.CharField(blank=True, max_length=50, null=True)),
                ('synced_from_biotime', models.BooleanField(default=False)),
                ('is_leave', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotime_server_url', models.URLField(max_length=255)),
                ('api_key', models.CharField(max_length=255)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_failure_message', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_health_status', models.CharField(choices=[('OK', 'سليم'), ('FAILURE', 'فشل'), ('AUTO_DISABLED', 'تم الإيقاف تلقائيًا')], default='OK', max_length=20)),
                ('auto_disabled_at', models.DateTimeField(blank=True, null=True)),
                ('work_start', models.TimeField(default=datetime.time(9, 0))),
                ('work_end', models.TimeField(default=datetime.time(17, 0))),
                ('grace_minutes', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_work_start', models.TimeField(blank=True, null=True)),
                ('custom_work_end', models.TimeField(blank=True, null=True)),
                ('custom_grace_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_overtime_enabled', models.BooleanField(blank=True, null=True)),
                ('custom_overtime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: دوام إداري، دوام ليلي، دوام مرن', max_length=150, verbose_name='اسم جدول الدوام')),
                ('schedule_type', models.CharField(choices=[('FULL_TIME', 'دوام كامل'), ('FLEXIBLE', 'دوام مرن (فترتين)'), ('HOURLY', 'دوام بالساعات')], default='FULL_TIME', max_length=20, verbose_name='نوع الدوام')),
                ('period1_start', models.TimeField(blank=True, null=True, verbose_name='بداية الفترة الأولى')),
                ('period1_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الفترة الأولى')),
                ('period2_start', models.TimeField(blank=True, null=True, verbose_name='بداية الفترة الثانية')),
                ('period2_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الفترة الثانية')),
                ('allow_night_overlap', models.BooleanField(default=True, help_text='يسمح بأن تمتد الفترة لليوم التالي تلقائيًا', verbose_name='السماح بالتداخل الليلي')),
                ('target_daily_hours', models.DecimalField(blank=True, decimal_places=2, help_text='يستخدم فقط في حالة الدوام بالساعات', max_digits=5, null=True, verbose_name='عدد ساعات الدوام اليومية')),
                ('early_arrival_minutes', models.PositiveIntegerField(default=0, verbose_name='السماح بالدخول المبكر (دقائق)')),
                ('early_exit_minutes', models.PositiveIntegerField(default=0, verbose_name='السماح بالخروج المبكر (دقائق)')),
                ('weekend_days', models.CharField(default='fri,sat', help_text='مثال: fri,sat أو sat أو tue', max_length=50, verbose_name='أيام الإجازة الأسبوعية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'جدول دوام',
                'verbose_name_plural': 'جداول الدوام',
                'ordering': ['name'],
            },
        ),
    ]
