# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_center', '0001_initial'),
        ('biotime_center', '0001_initial'),
        ('company_manager', '0001_initial'),
        ('employee_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_manager.company'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biotime_center.biotimedevice'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_policies', to='company_manager.company'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='biotime_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biotime_center.biotimelog'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_center.employee'),
        ),
        migrations.AddField(
            model_name='attendancesetting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='company_manager.company'),
        ),
        migrations.AddField(
            model_name='employeeattendancepolicy',
            name='company_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_center.attendancepolicy'),
        ),
        migrations.AddField(
            model_name='employeeattendancepolicy',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee_center.employee'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='company_manager.company', verbose_name='الشركة'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_82e510_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_day'),
        ),
    ]
