# Generated by Django 5.0.14 on 2026-01-30 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0002_initial'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الإجازة')),
                ('is_paid', models.BooleanField(default=True, verbose_name='إجازة مدفوعة')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='لون العرض')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'نوع إجازة',
                'verbose_name_plural': 'أنواع الإجازات',
            },
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='weekend_days',
            field=models.CharField(default='fri,sat', help_text='مثال: الجمعة,السبت أو sat,sun', max_length=50, verbose_name='أيام الإجازة الأسبوعية'),
        ),
        migrations.CreateModel(
            name='CompanyHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_paid', models.BooleanField(default=True, verbose_name='مدفوعة الأجر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='company_manager.company', verbose_name='الشركة')),
                ('holiday_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attendance_center.holidaytype', verbose_name='نوع الإجازة')),
            ],
            options={
                'verbose_name': 'إجازة رسمية',
                'verbose_name_plural': 'الإجازات الرسمية',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['company', 'start_date', 'end_date'], name='attendance__company_7d61c7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='companyholiday',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='holiday_end_date_after_start_date'),
        ),
    ]
