# Generated by Django 5.0.14 on 2026-02-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0003_holidaytype_alter_workschedule_weekend_days_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_attendance_per_employee_per_day',
        ),
        migrations.RemoveIndex(
            model_name='attendancerecord',
            name='attendance__employe_82e510_idx',
        ),
    ]
