# Generated by Django 5.0.14 on 2026-02-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0004_remove_attendancerecord_unique_attendance_per_employee_per_day_and_more'),
        ('biotime_center', '0006_biotimeemployee_linked_employee'),
        ('employee_center', '0004_remove_employee_biotime_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal Overtime'), ('WEEKEND', 'Weekend Overtime'), ('HOLIDAY', 'Holiday Overtime')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='attendance__employe_82e510_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_per_employee_per_day'),
        ),
    ]
