# Generated by Django 5.0.14 on 2026-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0005_attendancerecord_overtime_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='weekend_days',
            field=models.CharField(blank=True, default='', help_text='مثال: fri أو sat أو fri,sat', max_length=50, verbose_name='أيام الإجازة الأسبوعية'),
        ),
    ]
