# Generated by Django 5.0.14 on 2026-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0006_alter_workschedule_weekend_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'إجازة رسمية'), ('weekend', 'عطلة أسبوعية'), ('unknown', 'غير معروف')], default='present', max_length=10),
        ),
    ]
