# Generated by Django 5.0.14 on 2026-02-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0007_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='absence_threshold_minutes',
            field=models.PositiveIntegerField(default=60, help_text='بعد هذه المدة من بداية الدوام يتحول lifecycle_pending إلى غياب', verbose_name='مهلة قبل احتساب الغياب (دقائق)'),
        ),
    ]
