# Generated by Django 5.0.14 on 2026-02-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0008_attendancepolicy_absence_threshold_minutes'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_minutes', models.PositiveIntegerField(default=15, verbose_name='سماحية التأخير (دقائق)')),
                ('late_after_minutes', models.PositiveIntegerField(default=30, verbose_name='يعتبر متأخر بعد (دقائق)')),
                ('absence_after_minutes', models.PositiveIntegerField(default=180, verbose_name='يعتبر غائب بعد (دقائق)')),
                ('auto_absent_if_no_checkin', models.BooleanField(default=True, verbose_name='احتساب غياب تلقائي بدون تسجيل حضور')),
                ('overtime_enabled', models.BooleanField(default=True, verbose_name='تفعيل العمل الإضافي')),
                ('weekend_days', models.CharField(default='fri,sat', max_length=50, verbose_name='أيام الإجازة الأسبوعية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_setting_config', to='company_manager.company')),
            ],
        ),
    ]
