# Generated by Django 5.0.14 on 2026-02-15 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0009_companyattendancesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyattendancesetting',
            name='weekend_days',
        ),
    ]
