# Generated by Django 5.0.14 on 2026-02-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0010_remove_companyattendancesetting_weekend_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='مقفل نهائيًا'),
        ),
    ]
