# Generated by Django 5.0.14 on 2026-02-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0011_attendancerecord_finalized_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'إجازة رسمية'), ('weekend', 'عطلة أسبوعية'), ('not_started', 'قبل المباشرة'), ('unknown', 'غير معروف')], default='present', max_length=20),
        ),
    ]
