# Generated by Django 5.0.14 on 2026-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0012_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'حاضر'), ('late', 'متأخر'), ('absent', 'غائب'), ('leave', 'إجازة'), ('holiday', 'إجازة رسمية'), ('weekend', 'عطلة أسبوعية'), ('not_started', 'قبل المباشرة'), ('unknown', 'غير معروف'), ('terminated', 'منتهي خدمة')], default='present', max_length=20),
        ),
    ]
