# Generated by Django 5.0.14 on 2026-02-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_center', '0013_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='grace_minutes',
            field=models.PositiveIntegerField(default=0, help_text='عدد الدقائق المسموح بها بعد بداية الدوام بدون احتساب تأخير', verbose_name='سماحية التأخير (دقائق)'),
        ),
    ]
