# Generated by Django 5.0.14 on 2026-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyonboardingtransaction',
            name='admin_username',
            field=models.CharField(db_index=True, default='legacy_admin', help_text='Username الحقيقي للمسؤول', max_length=150),
            preserve_default=False,
        ),
    ]
