# Generated by Django 5.0.14 on 2026-03-06 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_center', '0002_companyonboardingtransaction_admin_username'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_reason',
            field=models.CharField(choices=[('NEW_SUBSCRIPTION', 'اشتراك جديد'), ('RENEWAL', 'تجديد الاشتراك'), ('UPGRADE', 'ترقية الباقة'), ('DOWNGRADE', 'تخفيض الباقة'), ('ADDON', 'إضافة خدمة')], default='NEW_SUBSCRIPTION', max_length=30),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='company_manager.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing_center.companysubscription'),
        ),
    ]
