# Generated by Django 5.0.14 on 2026-03-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_center', '0003_invoice_billing_reason_and_more'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='companysubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('company',), name='unique_active_subscription_per_company'),
        ),
    ]
