# Generated by Django 5.0.14 on 2026-03-14 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_center', '0004_companysubscription_unique_active_subscription_per_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='companyonboardingtransaction',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyonboardingtransaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PENDING_PAYMENT', 'بانتظار الدفع'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'حوالة'), ('CREDIT_CARD', 'بطاقة'), ('APPLE_PAY', 'Apple Pay'), ('STC_PAY', 'STC Pay'), ('TAMARA', 'Tamara'), ('CASH', 'كاش')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('card', 'بطاقة'), ('bank', 'حوالة'), ('stc', 'STC Pay'), ('apple', 'Apple Pay'), ('tamara', 'Tamara'), ('cash', 'كاش')], max_length=20),
        ),
    ]
