# Generated by Django 5.0.14 on 2026-03-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_center', '0005_invoice_subtotal_invoice_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyonboardingtransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BANK_TRANSFER', 'حوالة'), ('CREDIT_CARD', 'بطاقة'), ('APPLE_PAY', 'Apple Pay'), ('STC_PAY', 'STC Pay'), ('TAMARA', 'Tamara')], db_index=True, max_length=30, null=True),
        ),
    ]
