# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='العنوان المختصر للتحليل أو التوصية.', max_length=200, verbose_name='عنوان التحليل')),
                ('recommendation', models.TextField(help_text='النص الكامل للتحليل أو النتيجة التي تولدها الذكاء الاصطناعي.', verbose_name='نص التوصية / التحليل')),
                ('confidence', models.DecimalField(decimal_places=2, default=0.95, max_digits=5, verbose_name='نسبة الثقة بالتحليل')),
                ('context_summary', models.TextField(blank=True, help_text='ملخص ذكي يصف السياق أو البيانات التي استند إليها التحليل.', null=True, verbose_name='ملخص سياق التحليل')),
                ('source_module', models.CharField(blank=True, help_text='المصدر الذي استُخرجت منه البيانات (مثل Payroll / Attendance / Analytics).', max_length=100, null=True, verbose_name='الوحدة المصدر')),
                ('ai_tags', models.JSONField(default=list, help_text='قائمة بالوسوم الذكية المرتبطة بالتحليل.', verbose_name='وسوم تحليلية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('is_archived', models.BooleanField(default=False, verbose_name='مؤرشف؟')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_insights', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تحليل ذكي',
                'verbose_name_plural': 'التحليلات الذكية',
                'ordering': ['-created_at'],
            },
        ),
    ]
