# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
        ('employee_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_balance', models.PositiveIntegerField(default=21)),
                ('sick_balance', models.PositiveIntegerField(default=30)),
                ('maternity_balance', models.PositiveIntegerField(default=10)),
                ('marriage_balance', models.PositiveIntegerField(default=5)),
                ('death_balance', models.PositiveIntegerField(default=3)),
                ('hajj_balance', models.PositiveIntegerField(default=10)),
                ('study_balance', models.PositiveIntegerField(default=15)),
                ('unpaid_balance', models.PositiveIntegerField(default=999)),
                ('last_reset', models.DateField(blank=True, null=True)),
                ('auto_reset_enabled', models.BooleanField(default=True)),
                ('auto_reset_month', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='company_manager.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='employee_center.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('pending_manager', 'بانتظار المدير'), ('pending_hr', 'بانتظار HR'), ('approved', 'مقبول نهائي'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending_manager', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_approved_at', models.DateTimeField(blank=True, null=True)),
                ('hr_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_manager.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_center.employee')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('manager', 'موافقة المدير'), ('hr', 'موافقة HR'), ('system', 'النظام')], max_length=20)),
                ('action', models.CharField(choices=[('approved', 'موافقة'), ('rejected', 'رفض'), ('cancelled', 'إلغاء')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='leave_center.leaverequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('maternity', 'إجازة أمومة'), ('marriage', 'إجازة زواج'), ('death', 'إجازة وفاة'), ('hajj', 'إجازة حج'), ('study', 'إجازة دراسية'), ('unpaid', 'إجازة بدون راتب')], default='annual', max_length=50)),
                ('annual_balance', models.PositiveIntegerField(default=0)),
                ('requires_manager_only', models.BooleanField(default=False)),
                ('requires_hr_only', models.BooleanField(default=False)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#0ea5e9', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_manager.company')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_center.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveWorkflowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('manager', 'مدير'), ('hr', 'موارد بشرية'), ('rejected', 'رفض'), ('cancelled', 'إلغاء')], max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_status', to='leave_center.leaverequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_balance', models.FloatField(default=0)),
                ('new_balance', models.FloatField(default=0)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_manager.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_center.employee')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
