# Generated by Django 5.0.14 on 2026-01-30 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('leave_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnnualLeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_days', models.PositiveIntegerField(default=21, help_text='عدد أيام الإجازة السنوية الممنوحة سنويًا')),
                ('carry_forward_enabled', models.BooleanField(default=True, help_text='هل يسمح بترحيل الرصيد المتبقي للسنة القادمة')),
                ('carry_forward_limit', models.PositiveIntegerField(default=15, help_text='الحد الأعلى للأيام التي يمكن ترحيلها')),
                ('reset_month', models.PositiveSmallIntegerField(default=1, help_text='شهر إعادة تعيين رصيد الإجازة السنوية')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annual_leave_policy', to='company_manager.company')),
            ],
            options={
                'verbose_name': 'Company Annual Leave Policy',
                'verbose_name_plural': 'Company Annual Leave Policies',
            },
        ),
    ]
