# Generated by Django 5.0.14 on 2026-02-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('leave_center', '0002_companyannualleavepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_days', models.PositiveIntegerField(default=0, help_text='عدد الأيام الأساسية سنويًا')),
                ('min_service_years', models.PositiveIntegerField(blank=True, help_text='الحد الأدنى لسنوات الخدمة لتطبيق days_after_service', null=True)),
                ('days_after_service', models.PositiveIntegerField(blank=True, help_text='عدد الأيام بعد تجاوز سنوات الخدمة', null=True)),
                ('carry_forward_enabled', models.BooleanField(default=False)),
                ('carry_forward_limit', models.PositiveIntegerField(blank=True, help_text='الحد الأعلى للترحيل', null=True)),
                ('reset_month', models.PositiveSmallIntegerField(default=1, help_text='شهر إعادة تعيين الرصيد')),
                ('paid_leave', models.BooleanField(default=True)),
                ('requires_manager_approval', models.BooleanField(default=True)),
                ('requires_hr_approval', models.BooleanField(default=False)),
                ('max_consecutive_days', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_restriction', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policies', to='company_manager.company')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave_center.leavetype')),
            ],
            options={
                'verbose_name': 'Leave Policy',
                'verbose_name_plural': 'Leave Policies',
                'unique_together': {('company', 'leave_type')},
            },
        ),
    ]
