# Generated by Django 5.0.14 on 2026-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_center', '0003_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='pay_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pay percentage at time of approval (100 / 75 / 0)', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sick_calculated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when sick tier was calculated', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sick_days_counted',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sick days counted inside rolling window', null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='sick_tier',
            field=models.CharField(blank=True, help_text='Tier name returned from SickTierEngine (full / 75% / unpaid)', max_length=30, null=True),
        ),
    ]
