# Generated by Django 5.0.14 on 2026-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_center', '0004_leaverequest_pay_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='pay_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='sick_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='sick_days_counted',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='sick_tier',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
