# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
        ('employee_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PAYROLL', 'Payroll')], default='PAYROLL', max_length=20)),
                ('source_id', models.PositiveIntegerField(help_text='PayrollRun ID')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(help_text='e.g. 5100, 2100', max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll_center.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الراتب الأساسي')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='البدلات')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصومات')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المكافآت')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الإضافي')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الراتب')),
                ('month', models.DateField(verbose_name='شهر الراتب')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'مدفوع')], default='PENDING', max_length=20, verbose_name='حالة الراتب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='employee_center.contract', verbose_name='العقد')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employee_center.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل راتب',
                'verbose_name_plural': 'سجلات الرواتب',
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء السجل'), ('UPDATE', 'تحديث البيانات'), ('MARK_PAID', 'صرف الراتب')], max_length=20, verbose_name='نوع العملية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت العملية')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='payroll_center.payrollrecord', verbose_name='سجل الراتب')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
            ],
            options={
                'verbose_name': 'سجل عملية راتب',
                'verbose_name_plural': 'سجلات عمليات الرواتب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='يمثل أول يوم في الشهر', verbose_name='شهر دورة الرواتب')),
                ('status', models.CharField(choices=[('DRAFT', 'مسودة'), ('CALCULATED', 'محسوبة'), ('APPROVED', 'معتمدة'), ('PAID', 'مدفوعة')], default='DRAFT', max_length=20, verbose_name='حالة الدورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='company_manager.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'دورة رواتب',
                'verbose_name_plural': 'دورات الرواتب',
                'ordering': ['-month', '-created_at'],
                'unique_together': {('company', 'month')},
            },
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='payroll_center.payrollrun', verbose_name='دورة الرواتب'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'month')},
        ),
    ]
