# Generated by Django 5.0.14 on 2026-02-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('payroll_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_multiplier', models.FloatField(default=1.0)),
                ('overtime_multiplier', models.FloatField(default=1.5)),
                ('weekend_multiplier', models.FloatField(default=2.0)),
                ('holiday_multiplier', models.FloatField(default=2.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_policy', to='company_manager.company')),
            ],
        ),
    ]
