# Generated by Django 5.0.14 on 2026-02-08 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('payroll_center', '0002_companyovertimepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOvertimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
                ('weekend_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_setting', to='company_manager.company')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyOvertimePolicy',
        ),
    ]
