# Generated by Django 5.0.14 on 2026-02-11 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0007_employee_drive_file_id_alter_employee_photo_url'),
        ('payroll_center', '0003_companyovertimesetting_delete_companyovertimepolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll_center.payrollrun', verbose_name='دورة الرواتب'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together={('employee', 'run')},
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADDITION', 'إضافة'), ('DEDUCTION', 'خصم')], max_length=20, verbose_name='نوع العملية')),
                ('category', models.CharField(choices=[('BONUS', 'مكافأة'), ('ADVANCE', 'سلفة'), ('PENALTY', 'جزاء'), ('CORRECTION', 'تصحيح'), ('OTHER', 'أخرى')], default='OTHER', max_length=20, verbose_name='التصنيف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب / الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='employee_center.employee', verbose_name='الموظف')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll_center.payrollrun', verbose_name='دورة الرواتب')),
            ],
            options={
                'verbose_name': 'إضافة / خصم راتب',
                'verbose_name_plural': 'إضافات وخصومات الرواتب',
                'ordering': ['-created_at'],
            },
        ),
    ]
