# Generated by Django 5.0.14 on 2026-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_center', '0004_alter_payrollrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='breakdown',
            field=models.JSONField(blank=True, null=True, verbose_name='تفاصيل احتساب الراتب (Snapshot)'),
        ),
    ]
