# Generated by Django 5.0.14 on 2026-02-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_center', '0005_payrollrecord_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف'),
        ),
        migrations.AddField(
            model_name='payrollrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدًا'), ('BANK', 'تحويل بنكي')], max_length=20, null=True, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('PAYROLL', 'Payroll'), ('PAYROLL_PAYMENT', 'Payroll Payment')], default='PAYROLL', max_length=20),
        ),
    ]
