# Generated by Django 5.0.14 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_center', '0006_payrollrecord_paid_at_payrollrecord_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_id',
            field=models.PositiveIntegerField(help_text='Reference ID (PayrollRun or PayrollRecord ID)'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='unique_journalentry_source_sourceid'),
        ),
    ]
