# Generated by Django 5.0.14 on 2026-02-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('payroll_center', '0007_alter_journalentry_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='company_manager.company', verbose_name='الشركة'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date'], name='payroll_cen_company_9c80d7_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source'], name='payroll_cen_company_263d38_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'source', 'source_id'), name='unique_journalentry_company_source_sourceid'),
        ),
    ]
