# Generated by Django 5.0.14 on 2026-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_center', '0008_remove_journalentry_unique_journalentry_source_sourceid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'ordering': ['-month', '-created_at']},
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='month',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='overtime',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'نقدًا'), ('BANK', 'تحويل بنكي')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PAID', 'مدفوع')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
