# Generated by Django 5.0.14 on 2026-02-13 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('payroll_center', '0009_alter_payrollrecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSlipSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allowance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('breakdown', models.JSONField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_snapshots', to='company_manager.company')),
                ('payroll_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='payroll_center.payrollrecord', verbose_name='Payroll Record')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='payroll_center.payrollrun')),
            ],
            options={
                'verbose_name': 'Payroll Slip Snapshot',
                'verbose_name_plural': 'Payroll Slip Snapshots',
                'ordering': ['-frozen_at'],
            },
        ),
    ]
