# Generated by Django 5.0.14 on 2026-02-13 23:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('employee_center', '0007_employee_drive_file_id_alter_employee_photo_url'),
        ('payroll_center', '0010_payrollslipsnapshot'),
    ]

    operations = [

        migrations.AddField(
            model_name='payrollrecord',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='company_manager.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('PAYROLL', 'Payroll'), ('PAYROLL_PAYMENT', 'Payroll Payment')], db_index=True, default='PAYROLL', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_id',
            field=models.PositiveIntegerField(db_index=True, help_text='Reference ID (PayrollRun or PayrollRecord ID)'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records', to='employee_center.contract'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='employee_center.employee'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll_center.payrollrun'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('PARTIAL', 'مدفوع جزئياً'), ('PAID', 'مدفوع بالكامل')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source', 'source_id'], name='payroll_cen_company_ebfbd0_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'PAYROLL')), fields=('company', 'source', 'source_id'), name='unique_payroll_run_journal_per_company'),
        ),
    ]
