# Generated by Django 5.0.14 on 2026-02-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_center', '0011_remove_journalentry_unique_journalentry_source_sourceid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='unique_journalentry_source_sourceid',
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='unique_journalentry_company_source_sourceid',
        ),
    ]
