# Generated by Django 5.0.14 on 2026-01-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('subscription', 'تقارير الاشتراكات'), ('finance', 'التقارير المالية'), ('employees', 'تقارير الموظفين'), ('activity', 'سجلات النشاط'), ('ai_analysis', 'تحليل ذكي تلقائي')], max_length=50, verbose_name='نوع التقرير')),
                ('status', models.CharField(choices=[('READY', 'جاهز'), ('PENDING', 'قيد المعالجة'), ('FAILED', 'فشل')], default='READY', max_length=20, verbose_name='حالة التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='ملف التقرير (PDF أو Excel)')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='تم توليده تلقائيًا')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='التحليل الذكي التلقائي')),
                ('ai_score', models.FloatField(default=0.0, verbose_name='مؤشر الأداء العام (%)')),
            ],
            options={
                'verbose_name': 'تقرير ذكي',
                'verbose_name_plural': '📊 التقارير الذكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء تقرير'), ('UPDATE', 'تحديث تقرير'), ('GENERATE_AI', 'تحليل ذكي'), ('DELETE', 'حذف تقرير')], max_length=50, verbose_name='نوع العملية')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية أو رسالة النظام')),
            ],
            options={
                'verbose_name': 'سجل تقرير ذكي',
                'verbose_name_plural': '🧾 سجلات التقارير الذكية',
                'ordering': ['-executed_at'],
            },
        ),
    ]
