# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_center', '0001_initial'),
        ('company_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biotime_code', models.CharField(blank=True, db_index=True, help_text='Employee code in Biotime / biometric devices', max_length=50, null=True, verbose_name='كود الموظف في Biotime')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('arabic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id', models.CharField(max_length=20, verbose_name='رقم الهوية/الإقامة')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('probation', 'فترة تجريبية'), ('on_leave', 'في إجازة'), ('resigned', 'مستقيل'), ('terminated', 'تم إنهاء الخدمة')], default='active', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'دوام كامل'), ('part_time', 'دوام جزئي'), ('contract', 'عقد مؤقت'), ('seasonal', 'موسمي')], default='full_time', max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('probation_end_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company_manager.company', verbose_name='الشركة')),
                ('default_work_schedule', models.ForeignKey(blank=True, help_text='في حال تحديده يتم اعتماده مباشرة، وإلا يتم الرجوع لجدول القسم ثم الشركة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_as_default', to='attendance_center.workschedule', verbose_name='جدول الدوام الخاص بالموظف')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_employees', to='company_manager.companydepartment')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobtitle_employees', to='company_manager.jobtitle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_employee', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100)),
                ('contract_type', models.CharField(choices=[('fixed', 'محدد المدة'), ('unlimited', 'غير محدد'), ('temporary', 'مؤقت'), ('seasonal', 'موسمي'), ('part_time', 'دوام جزئي')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('probation_period_months', models.PositiveIntegerField(default=3)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('housing', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_renewable', models.BooleanField(default=True)),
                ('verify_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company_manager.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='employee_center.employee')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee_center.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('hire', 'تعيين'), ('promotion', 'ترقية'), ('transfer', 'نقل'), ('salary_change', 'تعديل راتب'), ('termination', 'إنهاء خدمة'), ('resignation', 'استقالة'), ('eosb_auto', 'مكافأة نهاية الخدمة تلقائيًا'), ('eosb_created', 'إنشاء مكافأة نهاية الخدمة')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='employee_center.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('job_level', models.CharField(blank=True, max_length=50, null=True)),
                ('job_category', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=200, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=200, null=True)),
                ('shift_type', models.CharField(choices=[('fixed', 'دوام ثابت'), ('shift', 'شفتات'), ('remote', 'عمل عن بعد'), ('hybrid', 'مختلط')], default='fixed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of', to='employee_center.employee')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_info', to='employee_center.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_gosi_enabled', models.BooleanField(default=True)),
                ('is_tax_enabled', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('iban', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='employee_center.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ResignationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignation_records', to='employee_center.employee')),
            ],
            options={
                'verbose_name': 'سجل استقالة',
                'verbose_name_plural': 'سجلات الاستقالة',
                'ordering': ['-resignation_date'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('employees', 'Employees'), ('departments', 'Departments'), ('job_titles', 'Job Titles')], max_length=30, verbose_name='نوع المزامنة')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='success', max_length=20, verbose_name='الحالة')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='إجمالي السجلات')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='عدد الناجح')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='عدد الفاشل')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='بدأت في')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهت في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_sync_logs', to='company_manager.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سجل مزامنة',
                'verbose_name_plural': 'سجلات المزامنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TerminationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_date', models.DateField(verbose_name='تاريخ إنهاء الخدمة')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الإنهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إدارية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_records', to='employee_center.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل إنهاء خدمة',
                'verbose_name_plural': 'سجلات إنهاء الخدمة',
                'ordering': ['-termination_date'],
            },
        ),
        migrations.CreateModel(
            name='EoSBRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_service', models.DecimalField(decimal_places=2, max_digits=6)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_method', models.CharField(choices=[('auto', 'حساب تلقائي'), ('manual', 'حساب يدوي')], default='auto', max_length=50, verbose_name='طريقة الحساب')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('calculation_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eosb_records', to='employee_center.employee', verbose_name='الموظف')),
                ('termination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eosb_records', to='employee_center.terminationrecord', verbose_name='سجل الإنهاء')),
            ],
            options={
                'verbose_name': 'مكافأة نهاية الخدمة',
                'verbose_name_plural': 'مكافآت نهاية الخدمة',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
