# Generated by Django 5.0.14 on 2026-01-24 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0001_initial'),
        ('employee_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biotime_employee',
            field=models.OneToOneField(blank=True, help_text='الربط الفعلي مع سجل الموظف في نظام Biotime بعد التحقق والمزامنة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_employee', to='biotime_center.biotimeemployee', verbose_name='الموظف المرتبط في Biotime'),
        ),
    ]
