# Generated by Django 5.0.14 on 2026-01-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('employee_center', '0002_employee_biotime_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='يمكن ربط الموظف بأكثر من فرع (Multi-Branch Support)', related_name='employees', to='company_manager.companybranch', verbose_name='الفروع المرتبط بها الموظف'),
        ),
    ]
