# Generated by Django 5.0.14 on 2026-02-07 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0003_employee_branches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='biotime_employee',
        ),
    ]
