# Generated by Django 5.0.14 on 2026-02-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0004_remove_employee_biotime_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='رقم الموظف الداخلي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gosi_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التأمينات الاجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='national_id_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الجواز'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الجواز'),
        ),
    ]
