# Generated by Django 5.0.14 on 2026-02-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0005_employee_employee_number_employee_gosi_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, help_text='يتم حفظ رابط الصورة من Google Drive', null=True, verbose_name='رابط صورة الموظف'),
        ),
    ]
