# Generated by Django 5.0.14 on 2026-02-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0006_employee_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Drive File ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط صورة الموظف'),
        ),
    ]
