# Generated by Django 5.0.14 on 2026-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0007_employee_drive_file_id_alter_employee_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الجوال'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_start_date',
            field=models.DateField(blank=True, help_text='يبدأ احتساب الحضور من هذا التاريخ', null=True, verbose_name='تاريخ المباشرة'),
        ),
    ]
