# Generated by Django 5.0.14 on 2026-03-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_center', '0008_employee_mobile_number_employee_work_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='drive_file_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_url',
            field=models.URLField(blank=True, db_index=True, help_text='Google Drive public image URL', null=True, verbose_name='رابط صورة الموظف'),
        ),
    ]
