# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiotimeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(unique=True)),
                ('sn', models.CharField(max_length=150)),
                ('alias', models.CharField(max_length=150)),
                ('terminal_name', models.CharField(blank=True, max_length=150, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('push_ver', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(default=0)),
                ('terminal_tz', models.IntegerField(blank=True, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('area_code', models.CharField(blank=True, max_length=100, null=True)),
                ('area_name', models.CharField(blank=True, max_length=150, null=True)),
                ('company_id', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('user_count', models.IntegerField(blank=True, null=True)),
                ('fp_count', models.IntegerField(blank=True, null=True)),
                ('face_count', models.IntegerField(blank=True, null=True)),
                ('palm_count', models.IntegerField(blank=True, null=True)),
                ('transaction_count', models.IntegerField(blank=True, null=True)),
                ('push_time', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_time', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_interval', models.IntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiotimeEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('position', models.CharField(blank=True, max_length=150, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolled_fingers', models.PositiveIntegerField(default=0)),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiotimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.IntegerField(unique=True)),
                ('employee_code', models.CharField(max_length=100)),
                ('punch_time', models.DateTimeField()),
                ('punch_state', models.CharField(max_length=10)),
                ('verify_type', models.IntegerField(default=0)),
                ('work_code', models.CharField(blank=True, max_length=10, null=True)),
                ('device_sn', models.CharField(max_length=150)),
                ('terminal_alias', models.CharField(blank=True, max_length=150, null=True)),
                ('area_alias', models.CharField(blank=True, max_length=150, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BiotimeSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('devices_synced', models.PositiveIntegerField(default=0)),
                ('employees_synced', models.PositiveIntegerField(default=0)),
                ('logs_synced', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'نجاح'), ('FAILED', 'فشل'), ('PARTIAL', 'جزئي')], default='SUCCESS', max_length=20)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiotimeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_url', models.URLField(max_length=255, verbose_name='🌐 رابط الخادم')),
                ('biotime_company', models.CharField(db_index=True, help_text='اسم الشركة داخل منصة Biotime Cloud مثل: demozkdxb', max_length=150, verbose_name='☁️ Biotime Tenant')),
                ('email', models.CharField(max_length=150, verbose_name='📧 البريد الإلكتروني')),
                ('password', models.CharField(max_length=255, verbose_name='🔑 كلمة المرور')),
                ('jwt_token', models.TextField(blank=True, null=True, verbose_name='🔐 رمز JWT')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='⏳ انتهاء صلاحية الرمز')),
                ('last_login_status', models.CharField(blank=True, max_length=20, null=True, verbose_name='📡 حالة آخر تسجيل دخول')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='🕒 وقت آخر تسجيل دخول')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_settings', to='company_manager.company', verbose_name='🏢 شركة Primey')),
            ],
            options={
                'verbose_name': 'Biotime Setting',
                'verbose_name_plural': 'Biotime Settings',
                'unique_together': {('company', 'biotime_company')},
            },
        ),
    ]
