# Generated by Django 5.0.14 on 2026-02-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0001_initial'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biotimesetting',
            options={},
        ),
        migrations.AddField(
            model_name='biotimeemployee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotime_employees', to='company_manager.company'),
        ),
        migrations.AlterField(
            model_name='biotimeemployee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='biotime_company',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_settings', to='company_manager.company'),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='last_login_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='server_url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biotimesetting',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='biotimeemployee',
            index=models.Index(fields=['company', 'employee_id'], name='biotime_cen_company_c6399d_idx'),
        ),
        migrations.AddConstraint(
            model_name='biotimeemployee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_id'), name='unique_biotime_employee_per_company'),
        ),
    ]
