# Generated by Django 5.0.14 on 2026-02-05 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0002_alter_biotimesetting_options_biotimeemployee_company_and_more'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biotimedevice',
            old_name='company_id',
            new_name='biotime_company_code',
        ),
        migrations.AddField(
            model_name='biotimedevice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotime_devices', to='company_manager.company'),
        ),
        migrations.AddField(
            model_name='biotimelog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biotime_logs', to='company_manager.company'),
        ),
        migrations.AddIndex(
            model_name='biotimedevice',
            index=models.Index(fields=['company', 'device_id'], name='biotime_cen_company_ccce81_idx'),
        ),
        migrations.AddIndex(
            model_name='biotimelog',
            index=models.Index(fields=['company', 'log_id'], name='biotime_cen_company_c7d704_idx'),
        ),
        migrations.AddIndex(
            model_name='biotimelog',
            index=models.Index(fields=['company', 'employee_code'], name='biotime_cen_company_e41c7b_idx'),
        ),
    ]
