# Generated by Django 5.0.14 on 2026-02-06 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0003_rename_company_id_biotimedevice_biotime_company_code_and_more'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biotimedevice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_devices', to='company_manager.company'),
        ),
        migrations.AlterField(
            model_name='biotimeemployee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_employees', to='company_manager.company'),
        ),
        migrations.AlterField(
            model_name='biotimelog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_logs', to='company_manager.company'),
        ),
    ]
