# Generated by Django 5.0.14 on 2026-02-07 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0004_alter_biotimedevice_company_and_more'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('employee_center', '0003_employee_branches'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiotimeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced_snapshot', models.JSONField(blank=True, default=dict)),
                ('dirty_fields', models.JSONField(blank=True, default=list)),
                ('is_dirty', models.BooleanField(default=False)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_sync_states', to='company_manager.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biotime_sync_state', to='employee_center.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'is_dirty'], name='biotime_cen_company_d436f0_idx')],
                'unique_together': {('company', 'employee')},
            },
        ),
    ]
