# Generated by Django 5.0.14 on 2026-02-07 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0005_biotimesyncstate'),
        ('employee_center', '0004_remove_employee_biotime_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotimeemployee',
            name='linked_employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biotime_record', to='employee_center.employee'),
        ),
    ]
