# Generated by Django 5.0.14 on 2026-02-18 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biotime_center', '0006_biotimeemployee_linked_employee'),
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biotimesynclog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='biotime_sync_logs', to='company_manager.company'),
            preserve_default=False,
        ),
    ]
