# Generated by Django 5.0.14 on 2026-04-01 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('notification_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(db_index=True, default='system', max_length=50, verbose_name='نوع الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='severity',
            field=models.CharField(db_index=True, default='info', max_length=20, verbose_name='مستوى الإشعار'),
        ),
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.CharField(db_index=True, max_length=100, verbose_name='كود الحدث')),
                ('event_group', models.CharField(db_index=True, default='system', max_length=50, verbose_name='مجموعة الحدث')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20, verbose_name='مستوى الحدث')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='حالة الحدث')),
                ('language_code', models.CharField(db_index=True, default='ar', max_length=10, verbose_name='رمز اللغة')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الموديل المستهدف')),
                ('target_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='معرف الكيان المستهدف')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان الافتراضي')),
                ('message', models.TextField(blank=True, null=True, verbose_name='الرسالة الافتراضية')),
                ('link', models.CharField(blank=True, max_length=300, null=True, verbose_name='الرابط الداخلي')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='بيانات الحدث')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='مصدر الحدث')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notification_events', to=settings.AUTH_USER_MODEL, verbose_name='منفذ الحدث')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='company_manager.company', verbose_name='الشركة')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notification_events', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستهدف')),
            ],
            options={
                'verbose_name': 'حدث تنبيهي',
                'verbose_name_plural': 'الأحداث التنبيهية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('push', 'Push')], db_index=True, max_length=20, verbose_name='القناة')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='حالة التسليم')),
                ('destination', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوجهة')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان/الموضوع')),
                ('rendered_message', models.TextField(blank=True, null=True, verbose_name='المحتوى المرسل')),
                ('template_key', models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='مفتاح القالب')),
                ('language_code', models.CharField(db_index=True, default='ar', max_length=10, verbose_name='رمز اللغة')),
                ('provider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المزود')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='معرف الرسالة عند المزود')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='استجابة المزود')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='أقصى عدد للمحاولات')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر محاولة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='company_manager.company', verbose_name='الشركة')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='notification_center.notification', verbose_name='الإشعار الداخلي المرتبط')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المستلم')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notification_center.notificationevent', verbose_name='الحدث')),
            ],
            options={
                'verbose_name': 'سجل تسليم',
                'verbose_name_plural': 'سجلات التسليم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notification_center.notificationevent', verbose_name='الحدث المرتبط'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_f28ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_c78193_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', '-created_at'], name='notificatio_company_3e4b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'severity'], name='notificatio_notific_9983cf_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_code', '-created_at'], name='notificatio_event_c_5112be_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['event_group', '-created_at'], name='notificatio_event_g_892b45_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['company', '-created_at'], name='notificatio_company_e08664_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['target_user', '-created_at'], name='notificatio_target__f32efc_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_80e75d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['severity', '-created_at'], name='notificatio_severit_5d6103_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationevent',
            index=models.Index(fields=['language_code', '-created_at'], name='notificatio_languag_7d8d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event', 'channel'], name='notificatio_event_i_7e9394_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['recipient', 'channel'], name='notificatio_recipie_74b0b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'channel'], name='notificatio_status_10b042_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['company', '-created_at'], name='notificatio_company_85f3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['provider_message_id'], name='notificatio_provide_3f258d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['template_key', 'language_code'], name='notificatio_templat_5caee2_idx'),
        ),
    ]
