# Generated by Django 5.0.14 on 2026-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('whatsapp_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='allow_broadcasts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='default_country_code',
            field=models.CharField(default='966', max_length=10),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='default_test_recipient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='send_test_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_connected_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_device_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_last_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_mode',
            field=models.CharField(choices=[('qr', 'QR'), ('pairing_code', 'Pairing Code')], default='qr', max_length=30),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_pairing_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='session_status',
            field=models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_pending', 'QR Pending'), ('pair_pending', 'Pair Pending'), ('connected', 'Connected'), ('failed', 'Failed')], default='disconnected', max_length=30),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='webhook_callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='companywhatsappconfig',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='allow_broadcasts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='default_country_code',
            field=models.CharField(default='966', max_length=10),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='default_test_recipient',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='send_test_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_connected_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_device_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_last_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_mode',
            field=models.CharField(choices=[('qr', 'QR'), ('pairing_code', 'Pairing Code')], default='qr', max_length=30),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_name',
            field=models.CharField(default='primey-system-session', max_length=255),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_pairing_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_qr_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='session_status',
            field=models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_pending', 'QR Pending'), ('pair_pending', 'Pair Pending'), ('connected', 'Connected'), ('failed', 'Failed')], default='disconnected', max_length=30),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='webhook_callback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='systemwhatsappconfig',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companywhatsappconfig',
            name='provider',
            field=models.CharField(choices=[('META', 'Meta'), ('TWILIO', 'Twilio'), ('UNIFONIC', 'Unifonic'), ('OTHER', 'Other'), ('whatsapp_web_session', 'WhatsApp Web Session'), ('meta_cloud_api', 'Meta Cloud API')], default='whatsapp_web_session', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemwhatsappconfig',
            name='provider',
            field=models.CharField(choices=[('META', 'Meta'), ('TWILIO', 'Twilio'), ('UNIFONIC', 'Unifonic'), ('OTHER', 'Other'), ('whatsapp_web_session', 'WhatsApp Web Session'), ('meta_cloud_api', 'Meta Cloud API')], default='whatsapp_web_session', max_length=50),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='provider',
            field=models.CharField(choices=[('META', 'Meta'), ('TWILIO', 'Twilio'), ('UNIFONIC', 'Unifonic'), ('OTHER', 'Other'), ('whatsapp_web_session', 'WhatsApp Web Session'), ('meta_cloud_api', 'Meta Cloud API')], default='META', max_length=50),
        ),
        migrations.AddIndex(
            model_name='companywhatsappconfig',
            index=models.Index(fields=['provider'], name='whatsapp_ce_provide_fbe5b3_idx'),
        ),
        migrations.AddIndex(
            model_name='companywhatsappconfig',
            index=models.Index(fields=['session_status'], name='whatsapp_ce_session_ec4043_idx'),
        ),
    ]
