# Generated by Django 5.0.14 on 2026-03-17 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('whatsapp_center', '0002_companywhatsappconfig_allow_broadcasts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='approval_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='provider_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'Not Synced'), ('SYNCED', 'Synced'), ('FAILED', 'Failed')], default='NOT_SYNCED', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['approval_status'], name='whatsapp_ce_approva_85bf31_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['provider_status'], name='whatsapp_ce_provide_09ab26_idx'),
        ),
    ]
