# Generated by Django 5.0.14 on 2026-03-23 04:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('whatsapp_center', '0003_whatsapptemplate_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], default='SYSTEM', max_length=20)),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be in international format, e.g. +9665XXXXXXXX', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('push_name', models.CharField(blank=True, max_length=255)),
                ('wa_jid', models.CharField(blank=True, max_length=255)),
                ('profile_name', models.CharField(blank=True, max_length=255)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_business', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='company_manager.company')),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], default='SYSTEM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('SPAM', 'Spam')], default='OPEN', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('session_name', models.CharField(blank=True, max_length=255)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_preview', models.TextField(blank=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whatsapp_conversations', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversations', to='company_manager.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='whatsapp_center.whatsappcontact')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation',
                'verbose_name_plural': 'WhatsApp Conversations',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('SYSTEM', 'System'), ('COMPANY', 'Company')], default='SYSTEM', max_length=20)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=20)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('TEMPLATE', 'Template'), ('DOCUMENT', 'Document')], default='TEXT', max_length=20)),
                ('external_message_id', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[('META', 'Meta'), ('TWILIO', 'Twilio'), ('UNIFONIC', 'Unifonic'), ('OTHER', 'Other'), ('whatsapp_web_session', 'WhatsApp Web Session'), ('meta_cloud_api', 'Meta Cloud API')], default='whatsapp_web_session', max_length=50)),
                ('provider_status', models.CharField(blank=True, max_length=255)),
                ('delivery_status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('wa_jid', models.CharField(blank=True, max_length=255)),
                ('sender_phone', models.CharField(blank=True, max_length=20)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True)),
                ('attachment_url', models.URLField(blank=True)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('media_type', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_from_me', models.BooleanField(default=False)),
                ('replied_to_external_message_id', models.CharField(blank=True, max_length=255)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('extra_json', models.JSONField(blank=True, default=dict)),
                ('message_created_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversation_messages', to='company_manager.company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_center.whatsappconversation')),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='whatsapp_center.whatsappmessagelog')),
                ('webhook_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='whatsapp_center.whatsappwebhookevent')),
            ],
            options={
                'verbose_name': 'WhatsApp Conversation Message',
                'verbose_name_plural': 'WhatsApp Conversation Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['scope_type', 'phone_number'], name='whatsapp_ce_scope_t_b4cc8f_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['company', 'phone_number'], name='whatsapp_ce_company_a32ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['last_message_at'], name='whatsapp_ce_last_me_a3d5ea_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['is_blocked'], name='whatsapp_ce_is_bloc_a260b8_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['scope_type', 'status'], name='whatsapp_ce_scope_t_f732de_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['company', 'status'], name='whatsapp_ce_company_a90386_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['contact', 'status'], name='whatsapp_ce_contact_5e6485_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['assigned_to'], name='whatsapp_ce_assigne_ff063c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['last_message_at'], name='whatsapp_ce_last_me_adf761_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['is_pinned'], name='whatsapp_ce_is_pinn_3037ac_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['is_resolved'], name='whatsapp_ce_is_reso_db1c2c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='whatsapp_ce_convers_c98620_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['scope_type', 'created_at'], name='whatsapp_ce_scope_t_1a0f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['company', 'created_at'], name='whatsapp_ce_company_91e68a_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['direction'], name='whatsapp_ce_directi_b10317_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['delivery_status'], name='whatsapp_ce_deliver_f5bbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['external_message_id'], name='whatsapp_ce_externa_bcfa16_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['sender_phone'], name='whatsapp_ce_sender__5dcc63_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['message_created_at'], name='whatsapp_ce_message_9d7277_idx'),
        ),
    ]
