# Generated by Django 5.0.14 on 2026-04-01 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_manager', '0002_companybranch_biotime_code_and_more'),
        ('employee_center', '0009_remove_employee_drive_file_id_and_more'),
        ('whatsapp_center', '0004_whatsappcontact_whatsappconversation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='systemwhatsappconfig',
            index=models.Index(fields=['is_enabled'], name='whatsapp_ce_is_enab_0c0c78_idx'),
        ),
        migrations.AddIndex(
            model_name='systemwhatsappconfig',
            index=models.Index(fields=['is_active'], name='whatsapp_ce_is_acti_9fe54e_idx'),
        ),
        migrations.AddIndex(
            model_name='systemwhatsappconfig',
            index=models.Index(fields=['provider'], name='whatsapp_ce_provide_9a9124_idx'),
        ),
        migrations.AddIndex(
            model_name='systemwhatsappconfig',
            index=models.Index(fields=['session_status'], name='whatsapp_ce_session_2a8739_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappbroadcast',
            index=models.Index(fields=['scope_type'], name='whatsapp_ce_scope_t_e7c182_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappbroadcastrecipient',
            index=models.Index(fields=['recipient_type'], name='whatsapp_ce_recipie_2c32c8_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcontact',
            index=models.Index(fields=['wa_jid'], name='whatsapp_ce_wa_jid_49ec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversation',
            index=models.Index(fields=['unread_count'], name='whatsapp_ce_unread__a48a35_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['is_read'], name='whatsapp_ce_is_read_92abed_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappconversationmessage',
            index=models.Index(fields=['is_from_me'], name='whatsapp_ce_is_from_720b15_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['trigger_source'], name='whatsapp_ce_trigger_b6e2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappreminderrule',
            index=models.Index(fields=['event_code'], name='whatsapp_ce_event_c_b91e73_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappreminderrule',
            index=models.Index(fields=['is_active'], name='whatsapp_ce_is_acti_a7589b_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['template_key'], name='whatsapp_ce_templat_214f71_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappwebhookevent',
            index=models.Index(fields=['provider'], name='whatsapp_ce_provide_c08722_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcontact',
            constraint=models.UniqueConstraint(fields=('scope_type', 'company', 'phone_number'), name='uniq_whatsapp_contact_scope_company_phone'),
        ),
        migrations.AddConstraint(
            model_name='whatsappconversation',
            constraint=models.UniqueConstraint(fields=('scope_type', 'company', 'contact'), name='uniq_whatsapp_conversation_scope_company_contact'),
        ),
    ]
