# Generated by Django 5.0.14 on 2026-01-24 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(help_text='مثال: employee_center, payroll_center, biotime_center', max_length=100, verbose_name='الوحدة')),
                ('action', models.CharField(help_text='مثال: create, update, delete, sync, login', max_length=100, verbose_name='الإجراء')),
                ('severity', models.CharField(choices=[('info', 'معلومة'), ('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], default='info', max_length=20, verbose_name='مستوى الخطورة')),
                ('message', models.TextField(help_text='وصف الحدث الذي حصل داخل النظام', verbose_name='الرسالة')),
                ('extra_data', models.JSONField(blank=True, help_text='تخزين أي تفاصيل إضافية (مثل قبل/بعد التعديل)', null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='company_manager.company', verbose_name='الشركة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المنفّذ')),
            ],
            options={
                'verbose_name': 'سجل نظام',
                'verbose_name_plural': 'سجلات النظام',
                'ordering': ['-created_at'],
            },
        ),
    ]
